// lib/features/dashboard/data/models/promotion_model.dart
import 'package:equatable/equatable.dart';

enum DiscountType {
  percentage,
  fixed,
  freeAddon;

  String get displayName {
    switch (this) {
      case DiscountType.percentage:
        return 'Percentage off';
      case DiscountType.fixed:
        return 'Fixed amount off';
      case DiscountType.freeAddon:
        return 'Free add-on';
    }
  }

  String get value {
    switch (this) {
      case DiscountType.percentage:
        return 'percentage';
      case DiscountType.fixed:
        return 'fixed';
      case DiscountType.freeAddon:
        return 'free_addon';
    }
  }

  static DiscountType fromString(String value) {
    switch (value) {
      case 'percentage':
        return DiscountType.percentage;
      case 'fixed':
        return DiscountType.fixed;
      case 'free_addon':
        return DiscountType.freeAddon;
      default:
        return DiscountType.percentage;
    }
  }
}

/// Promotion source — Phase 13. Differentiates the three creation
/// paths: owner-authored ('owner_defined'), trigger-generated on Nth
/// completed booking ('loyalty'), helper-generated by
/// enqueue_booking_reminder ('recovery'). System codes (loyalty,
/// recovery) are hidden from the owner's main list by default and
/// never editable.
enum PromoSource {
  ownerDefined,
  loyalty,
  recovery;

  String get displayName {
    switch (this) {
      case PromoSource.ownerDefined:
        return 'Owner';
      case PromoSource.loyalty:
        return 'Loyalty';
      case PromoSource.recovery:
        return 'Recovery';
    }
  }

  String get value {
    switch (this) {
      case PromoSource.ownerDefined:
        return 'owner_defined';
      case PromoSource.loyalty:
        return 'loyalty';
      case PromoSource.recovery:
        return 'recovery';
    }
  }

  static PromoSource fromString(String value) {
    switch (value) {
      case 'loyalty':
        return PromoSource.loyalty;
      case 'recovery':
        return PromoSource.recovery;
      case 'owner_defined':
      default:
        return PromoSource.ownerDefined;
    }
  }

  bool get isSystemGenerated =>
      this == PromoSource.loyalty || this == PromoSource.recovery;
}

class Promotion extends Equatable {
  final String id;
  final String shopId;
  final String name;
  final String code;
  final DiscountType discountType;
  final double discountValue;
  final DateTime validFrom;
  final DateTime validTo;
  final int? usageLimit;
  final int usageCount;
  final bool isActive;
  final DateTime createdAt;
  final DateTime updatedAt;

  // ── Phase 13 additions ────────────────────────────────────────────
  // All nullable / default-filled so existing rows in the DB and
  // existing callers that don't know about Phase 13 keep working.
  final PromoSource source;
  final String? targetUserId;
  final String? targetGuestProfileId;
  final int perClientMax;
  final double? minBookingAmount;
  final List<String>? serviceRestriction;
  final DateTime? archivedAt;

  const Promotion({
    required this.id,
    required this.shopId,
    required this.name,
    required this.code,
    required this.discountType,
    required this.discountValue,
    required this.validFrom,
    required this.validTo,
    this.usageLimit,
    this.usageCount = 0,
    this.isActive = true,
    required this.createdAt,
    required this.updatedAt,
    this.source = PromoSource.ownerDefined,
    this.targetUserId,
    this.targetGuestProfileId,
    this.perClientMax = 1,
    this.minBookingAmount,
    this.serviceRestriction,
    this.archivedAt,
  });

  /// Phase 13 — true for trigger/helper-generated rows. Hidden from the
  /// owner's main list by default; the row is never editable.
  bool get isSystemGenerated => source.isSystemGenerated;

  /// Phase 13 — soft-deleted via archive_promo flow. Excluded from
  /// validate_and_apply_promo lookups.
  bool get isArchived => archivedAt != null;

  bool get isExpired => validTo.isBefore(DateTime.now());
  bool get isUnlimited => usageLimit == null;
  bool get hasReachedLimit => usageLimit != null && usageCount >= usageLimit!;
  bool get isValid => isActive && !isExpired && !hasReachedLimit;

  String get formattedDiscount {
    switch (discountType) {
      case DiscountType.percentage:
        return '${discountValue.toStringAsFixed(0)}% off';
      case DiscountType.fixed:
        return '\$${discountValue.toStringAsFixed(2)} off';
      case DiscountType.freeAddon:
        return 'Free add-on';
    }
  }

  factory Promotion.fromJson(Map<String, dynamic> json) {
    return Promotion(
      id: json['id'],
      shopId: json['shop_id'],
      name: json['name'],
      code: json['code'].toUpperCase(),
      discountType: DiscountType.fromString(json['discount_type']),
      discountValue: (json['discount_value'] as num).toDouble(),
      validFrom: DateTime.parse(json['valid_from']),
      validTo: DateTime.parse(json['valid_to']),
      usageLimit: json['usage_limit'],
      usageCount: json['usage_count'] ?? 0,
      isActive: json['is_active'] ?? true,
      createdAt: DateTime.parse(json['created_at']),
      updatedAt: DateTime.parse(json['updated_at']),
      // Phase 13 — safely default-filled for pre-Phase-13 rows.
      source: json['source'] != null
          ? PromoSource.fromString(json['source'] as String)
          : PromoSource.ownerDefined,
      targetUserId: json['target_user_id'] as String?,
      targetGuestProfileId: json['target_guest_profile_id'] as String?,
      perClientMax: (json['per_client_max'] as int?) ?? 1,
      minBookingAmount: (json['min_booking_amount'] as num?)?.toDouble(),
      serviceRestriction: (json['service_restriction'] as List?)
          ?.map((e) => e as String)
          .toList(),
      archivedAt: json['archived_at'] != null
          ? DateTime.parse(json['archived_at'] as String)
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'shop_id': shopId,
      'name': name,
      'code': code.toUpperCase(),
      'discount_type': discountType.value,
      'discount_value': discountValue,
      'valid_from': validFrom.toIso8601String().split('T').first,
      'valid_to': validTo.toIso8601String().split('T').first,
      'usage_limit': usageLimit,
      'usage_count': usageCount,
      'is_active': isActive,
      // Phase 13 — these round-trip on owner-side reads. They are NOT
      // included in INSERT/UPDATE payloads from the owner UI (system
      // codes are read-only on the owner side; per_client_max et al.
      // are sent via a separate Phase 13 endpoint when needed).
      'source': source.value,
      'target_user_id': targetUserId,
      'target_guest_profile_id': targetGuestProfileId,
      'per_client_max': perClientMax,
      'min_booking_amount': minBookingAmount,
      'service_restriction': serviceRestriction,
      'archived_at': archivedAt?.toIso8601String(),
    };
  }

  Promotion copyWith({
    String? name,
    String? code,
    DiscountType? discountType,
    double? discountValue,
    DateTime? validFrom,
    DateTime? validTo,
    int? usageLimit,
    bool? isActive,
    int? perClientMax,
    double? minBookingAmount,
    List<String>? serviceRestriction,
    DateTime? archivedAt,
  }) {
    return Promotion(
      id: id,
      shopId: shopId,
      name: name ?? this.name,
      code: code ?? this.code,
      discountType: discountType ?? this.discountType,
      discountValue: discountValue ?? this.discountValue,
      validFrom: validFrom ?? this.validFrom,
      validTo: validTo ?? this.validTo,
      usageLimit: usageLimit ?? this.usageLimit,
      usageCount: usageCount,
      isActive: isActive ?? this.isActive,
      createdAt: createdAt,
      updatedAt: DateTime.now(),
      // Phase 13: source / target_* never change via copyWith — those
      // are server-decided on creation.
      source: source,
      targetUserId: targetUserId,
      targetGuestProfileId: targetGuestProfileId,
      perClientMax: perClientMax ?? this.perClientMax,
      minBookingAmount: minBookingAmount ?? this.minBookingAmount,
      serviceRestriction: serviceRestriction ?? this.serviceRestriction,
      archivedAt: archivedAt ?? this.archivedAt,
    );
  }

  @override
  List<Object?> get props => [
    id, shopId, name, code, discountType, discountValue,
    validFrom, validTo, usageLimit, usageCount, isActive,
    createdAt, updatedAt,
    source, targetUserId, targetGuestProfileId,
    perClientMax, minBookingAmount, serviceRestriction, archivedAt,
  ];
}
